export const Risk = [
  {
    title: "Catastrophic (Cat) Risk",
    property: [
      {
        id: "1",
        propertyTitle: { text: "Land", disabled: false },
        props: [
          {
            title: "Eartquake",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "LandSlide",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Sinkhole",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "F_Eartquake",
            disabled: true,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "2",
        propertyTitle: { text: "WATER", disabled: false },
        props: [
          {
            title: "Floodingc",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "F_Flood",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "R_Flood",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "C_Flood",
            disabled: true,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Reservoir",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "River",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Sea",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Lake",
            disabled: true,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "3",
        propertyTitle: { text: "WIND", disabled: false },
        props: [
          {
            title: "Hurricane",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Storm",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Typhoon",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Tornado",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Hail",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Ligtning",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "L_Strike",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "L_Probabillity",
            disabled: true,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "4",
        propertyTitle: { text: "Fire", disabled: false },
        props: [
          {
            title: "Bushfire",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Wildfire",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Cemical",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Fire_Post",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Fire-Station",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "S_Hydrant",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "E_Hydrant",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Hs-Area",
            disabled: true,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
    ],
  },
  {
    title: "Other Factors",
    property: [
      {
        id: "1",
        propertyTitle: { text: "LAND USE", disabled: false },
        props: [
          {
            title: "Comercial",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "industrial",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Residential",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Park",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Trees",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Bushes",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "O_Space",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Private",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Councill",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Granite",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Clay",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Soil",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "2",
        propertyTitle: { text: "WEATHER", disabled: false },
        props: [
          {
            title: "Rain",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Sun",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Snow",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Celsius",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Humidity",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "UV",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Precipitatn",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Cloudnines",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "3",
        propertyTitle: { text: "Crime", disabled: false },
        props: [
          {
            title: "Burglary",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Gun",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Gang",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Drugs",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "Car-Theft",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Fraud",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Police_Stn",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Police_Pst",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "4",
        propertyTitle: { text: "Demographic", disabled: false },
        props: [
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Population",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Nationality",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Gender",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "5",
        propertyTitle: { text: "ELEVATION", disabled: false },
        props: [
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Z_Value",
            disabled: false,
            checkbox: true,
            md: 3,
            icon: false,
          },
          {
            title: "Sea Level",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "Hight-Map",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
    ],
  },
  {
    title: "Building & Property",
    property: [
      {
        id: "1",
        propertyTitle: { text: "ATRIBUTES", disabled: false },
        props: [
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "",
            disabled: true,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
      {
        id: "2",
        propertyTitle: { text: "FACADE", disabled: false },
        props: [
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 2.5,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 3,
            icon: false,
          },
          {
            title: "",
            disabled: false,
            checkbox: false,
            md: 1,
            icon: true,
          },
        ],
      },
    ],
  },
];
export const clientInf = [
  {
    name: "Alwiyah Ahmad",
    location: "Singapore",
    value: "$50,000",
    police: "***032",
    age: "51",
  },
  {
    name: "Ang Wee Jun",
    location: "Singapore",
    value: "$100,000",
    police: "***024",
    age: "42",
  },
  {
    name: "Bala S. Muthu",
    location: "Singapore",
    value: "$90,000",
    police: "***039",
    age: "50",
  },
  {
    name: "B Anta Min",
    location: "Singapore",
    value: "$290,000",
    police: "***031",
    age: "37",
  },
  {
    name: "Iashin Malivd",
    location: "Singapore",
    value: "$20,000",
    police: "***032",
    age: "22",
  },
  {
    name: "Gata Bmatu",
    location: "Singapore",
    value: "$70,000",
    police: "***062",
    age: "46",
  },
];
export const clientPortfelio = [
  {
    policeType: "Home1-INSR",
    location: "serangoon",
    policyCount: "0028",
    insuredAmount: "$2,500,000",
    duration: "18yrs",
    avargeRiskGrade: "Grade: C|2.5",
  },
  {
    policeType: "Home2-INSR",
    location: "serangoon",
    policyCount: "1400",
    insuredAmount: "$6,000,000",
    duration: "20yrs",
    avargeRiskGrade: "Grade: B|1.5",
  },
  {
    policeType: "Auto-INSR",
    location: "serangoon",
    policyCount: "0325",
    insuredAmount: "$3,000,000",
    duration: "15yrs",
    avargeRiskGrade: "Grade: A|1.0",
  },
  {
    policeType: "Micro-INSR",
    location: "serangoon",
    policyCount: "0528",
    insuredAmount: "$4,500,000",
    duration: "10yrs",
    avargeRiskGrade: "Grade: C|3.5",
  },
  {
    policeType: "Home8-INSR",
    location: "serangoon",
    policyCount: "0228",
    insuredAmount: "$9,500,000",
    duration: "12yrs",
    avargeRiskGrade: "Grade: C|9.5",
  },
];

export const geoData = [
  {
    title: "Land Use",
    property: ["Land_Type", "Land_Owner", "Land_Cover", "Ground_Type"],
  },
  {
    title: "Water Bodies",
    property: ["Water_Type", "Water_Structure", "Flooding", "Water_Level"],
  },
  {
    title: "Weather",
    property: ["Weater_Type", "Weater_Structure"],
  },
  {
    title: "Elevation",
    property: ["Elevation_Type", "Elevation_Structure"],
  },
  {
    title: "Demographic",
    property: ["Demographic_Type", "Demographic_Structure"],
  },
  {
    title: "Crime",
    property: ["C_Type1", "C_Typoe2", "Police_Stations", "Crime_Rate"],
  },
];
