export const style = {
  header: (togle) => ({
    width: "100%",
    background: `url(${"/src/image/header.jpg"})`,
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    position: "fixed",
    left: 0,
    zIndex: 3,
    justifyContent: "flex-start",
    alignItems: "flex-start",
    textAlign: "center",
    ...(togle && {
      header: 120,
    }),
    transition: "all 1s ease",
  }),
  headerPropertyMainContainer: {
    width: "100%",
    height: 90,
    background: "transparent",
    zIndex: 4,
    position: "absolute",
    display: "flex",
    alignItems: "cetner",
    justifyContent: "center",
    mt: 2,
  },

  headerPropertyContainer: {
    borderTop: "2px solid white",
    background: "transparent",
    left: { md: "300px", xl: "600px" },
    display: "flex",
    height: 70,
    zIndex: 10,
    alignItems: "center",
    textAlign: "center",
    justifyContent: "flex-start",
    gap: 0.5,
  },
  headerCostumeBtn: {
    borderRadius: 1,
    border: "5px solid white",
    fontSize: "40px",
    background: "#2c86bf",
    color: "black",
    "&:hover": {
      background: "#26658c",
    },
  },
  personInformationContainer: {
    alignItems: "center",
    flexDirection: "row",
    gap: 0.5,
    p: 0.5,
  },
  circle: (leftColor, rightColor) => ({
    display: "inline-block",
    borderRight: `7px solid ${leftColor}`,
    borderTop: `7px solid ${leftColor}`,
    borderLeft: `7px solid ${rightColor}`,
    borderBottom: `7px solid ${rightColor}`,
    borderRadius: "7px",
    transform: "rotate(45deg)",
  }),
  headerPropsText: {
    color: "white",
    whiteSpace: "nowrap",
    fontSize: { md: "small", xl: "medium" },
  },
  exitContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyConten: "center",
    p: 0.5,
    gap: 0.6,
  },
  headerProfileContainer: {
    display: "flex",
    position: "fixed",
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  responsiveComponent: {
    width: "100%",
    transform: "translateY(-10px)",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  footerContainer: {
    width: "100%",
    height: "20px",
    position: "absolute",
    bottom: 29,
    left: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  footerComponentContainer: {
    flexDirection: "row",
    alignItems: "center",
    textAlign: "center",
  },
  textFieldsStyle: {
    border: "3px solid black",
    borderTop: "none",
    maxWidth: "150px",
    outline: "none",
    padding: "0 0.3rem",
    "& fieldset": { border: "none" },
    "& .css-8pr55k-MuiInputBase-root-MuiInput-root:before": {
      border: "none",
    },
    "& label.Mui-focused": {
      color: "none",
    },
    "& .MuiInput-underline:after": {
      border: "none",
    },
    "& .MuiOutlinedInput-root": {
      "& fieldset": {
        border: "white",
      },
      "&:hover fieldset": {
        border: "white",
      },
      "&.Mui-focused fieldset": {
        border: "white",
      },
    },
  },
};
